name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checar código
      uses: actions/checkout@v2

    - name: Configurar credencias da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalar dependências
      run: npm install

    - name: Build da aplicação
      run: npm run build

    - name: Logar no DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}


    - name: Instalar kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Instalar Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.8.0'

    - name: Testar Conexão com o Cluster
      run: |
        echo "${KUBE_CONFIG_DATA}" | base64 --decode > kubeconfig.yaml
        kubectl config use-context arn:aws:eks:us-east-1:891377113883:cluster/my-eks-cluster --kubeconfig=kubeconfig.yaml
        kubectl get nodes --kubeconfig=kubeconfig.yaml

    - name: Verificar Kubeconfig
      run: cat kubeconfig.yaml

    - name: Implantar com Helm
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "${KUBE_CONFIG_DATA}" | base64 --decode > kubeconfig.yaml
        chmod 600 kubeconfig.yaml
        kubectl config view --kubeconfig=kubeconfig.yaml
        helm upgrade --install my-app ./helm/my-app --kubeconfig kubeconfig.yaml

